"""
Question selector.

Takes a list of candidate questions (typically generated by `generator.py`)
and picks the best subset matching a target student level.

Uses Phase 4 (difficulty) and Phase 5 (Bloom's) classifiers to score each
candidate, then ranks and selects.
"""

from typing import Dict, List
from dataclasses import dataclass

from src.classifier.difficulty import DifficultyClassifier
from src.classifier.bloom import BloomClassifier
from src.config import QUIZ_FINAL_COUNT, QUIZ_LEVELS

# Forward-import only at type-check time to avoid circular imports
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from src.quiz.generator import MCQuestion

# Profiles defining what kind of question mix is appropriate for each level.
# Each profile gives a desired count for each (difficulty, bloom) bucket.
# The selector tries to fill these slots with available candidates.

LEVEL_PROFILES = {
    "beginner": {
        # Mostly easy LOTS, a couple medium LOTS for stretch
        ("easy", "LOTS"): 3,
        ("easy", "HOTS"): 1,
        ("medium", "LOTS"): 1,
    },
    "intermediate": {
        # Balanced mix
        ("easy", "LOTS"): 1,
        ("medium", "LOTS"): 1,
        ("medium", "HOTS"): 2,
        ("hard", "LOTS"): 1,
    },
    "advanced": {
        # Mostly hard HOTS
        ("medium", "HOTS"): 1,
        ("hard", "LOTS"): 1,
        ("hard", "HOTS"): 3,
    },
}


@dataclass
class ClassifiedQuestion:
    """A question with its classification metadata attached.

    For free-text mode, mcq_data is None.
    For MCQ mode, mcq_data carries the options and correct answer.
    """

    text: str
    difficulty: str
    bloom: str
    difficulty_confidence: float
    bloom_confidence: float
    mcq_data: "MCQuestion | None" = None       # set in MCQ mode

    @property
    def bucket(self) -> tuple[str, str]:
        """The (difficulty, bloom) tuple used for slot matching."""
        return (self.difficulty, self.bloom)

    @property
    def is_mcq(self) -> bool:
        """True if this question has MCQ data attached."""
        return self.mcq_data is not None


class QuestionSelector:
    """
    Selects a quiz from candidate questions, matched to a student level.

    Usage:
        selector = QuestionSelector()
        chosen = selector.select(candidates, student_level="intermediate")
        for q in chosen:
            print(f"[{q.difficulty}/{q.bloom}] {q.text}")

    The classifiers are loaded lazily on first use.
    """

    def __init__(
        self,
        difficulty_classifier: DifficultyClassifier | None = None,
        bloom_classifier: BloomClassifier | None = None,
    ):
        """
        Initialize the selector.

        Args:
            difficulty_classifier: Optional pre-loaded classifier (saves
                memory if other components share it).
            bloom_classifier: Same, for Bloom's classifier.
        """
        self.difficulty_classifier = difficulty_classifier or DifficultyClassifier()
        self.bloom_classifier = bloom_classifier or BloomClassifier()

    def classify(
        self,
        questions: list[str],
        mcq_data: "list[MCQuestion] | None" = None,
    ) -> list[ClassifiedQuestion]:
        """
        Run both classifiers on the candidate questions.

        Args:
            questions: List of question texts.
            mcq_data: Optional list of MCQuestion objects (same length as
                questions). When provided, each ClassifiedQuestion will
                carry its MCQ data.

        Returns:
            List of ClassifiedQuestion objects.
        """
        if not questions:
            return []

        difficulty_results = self.difficulty_classifier.predict_batch(questions)
        bloom_results = self.bloom_classifier.predict_batch(questions)

        classified: list[ClassifiedQuestion] = []
        for i, (q, diff, bloom) in enumerate(
            zip(questions, difficulty_results, bloom_results)
        ):
            mcq = mcq_data[i] if mcq_data and i < len(mcq_data) else None
            classified.append(ClassifiedQuestion(
                text=q,
                difficulty=diff["label"],
                bloom=bloom["label"],
                difficulty_confidence=diff["confidence"],
                bloom_confidence=bloom["confidence"],
                mcq_data=mcq,
            ))

        return classified
    def select(
        self,
        candidates: list[str],
        student_level: str,
        target_count: int = QUIZ_FINAL_COUNT,
        mcq_data: "list[MCQuestion] | None" = None,
    ) -> list[ClassifiedQuestion]:
        """
        Pick the best target_count questions matching the student level.

        Args:
            candidates: Candidate question texts.
            student_level: One of "beginner", "intermediate", "advanced".
            target_count: How many questions to pick.
            mcq_data: Optional MCQ data parallel to candidates.

        Returns:
            List of ClassifiedQuestion, length up to target_count.
        """
        if student_level not in QUIZ_LEVELS:
            raise ValueError(
                f"Invalid student level '{student_level}'. "
                f"Must be one of {QUIZ_LEVELS}."
            )
        if not candidates:
            raise ValueError("Candidates list cannot be empty.")

        classified = self.classify(candidates, mcq_data=mcq_data)
        profile = LEVEL_PROFILES[student_level]

        buckets: dict[tuple, list[ClassifiedQuestion]] = {}
        for q in classified:
            buckets.setdefault(q.bucket, []).append(q)

        chosen: list[ClassifiedQuestion] = []
        chosen_ids: set[int] = set()

        for bucket, desired_count in profile.items():
            available = buckets.get(bucket, [])
            available.sort(
                key=lambda q: q.difficulty_confidence + q.bloom_confidence,
                reverse=True,
            )
            for q in available[:desired_count]:
                chosen.append(q)
                chosen_ids.add(id(q))

        if len(chosen) < target_count:
            leftovers = [q for q in classified if id(q) not in chosen_ids]
            leftovers.sort(
                key=lambda q: q.difficulty_confidence + q.bloom_confidence,
                reverse=True,
            )
            needed = target_count - len(chosen)
            chosen.extend(leftovers[:needed])

        return chosen[:target_count]